t = float(input("DIGITE UM NÚMERO PARA VER A SUA TABUADA:"))
print("-" * 30)

print("{} x {} = {}".format(t, 1, t*1))
print("{} x {} = {}".format(t, 2, t*2))
print("{} x {} = {}".format(t, 3, t*3))
print("{} x {} = {}".format(t, 4, t*4))
print("{} x {} = {}".format(t, 5, t*15))
print("{} x {} = {}".format(t, 6, t*6))
print("{} x {} = {}".format(t, 7, t*7))
print("{} x {} = {}".format(t, 8, t*8))
print("{} x {} = {}".format(t, 9, t*9))
print("{} x {} = {}".format(t, 10, t*10))
print("-" * 30)